FROM node:16-alpine

# This is the private key of the first account generated by default by Hardhat.
# This is always the same, read more https://hardhat.org/hardhat-network/docs/reference#initial-state
# In order for Hardhat to deploy your smart contracts to Polygon Mumbai, an environment variable
# with the private key of your main account should be declared.
# 
ENV privateKey='ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80'

COPY . /usr/src/app

WORKDIR /usr/src/app

RUN apk add git;

RUN apk --no-cache add curl;

RUN yarn install --non-interactive

COPY $PWD/docker/entrypoint.sh /usr/local/bin

ENTRYPOINT ["/bin/sh", "/usr/local/bin/entrypoint.sh"]